spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREE
    username: C##VHO
    password: activ
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: true